language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9

install:
  - go get github.com/antchfx/xpath
  - go get github.com/mattn/goveralls
  - go get github.com/golang/groupcache
  
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci